import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting coder
        </h1>
        {/* <img src='/images/coder.webp' alt='coder image' /> */}
        <p className={styles.description}>
          A blog for hunting coders by hunting coder
        </p>
        <h2 className={styles.latest_blogs}>Latest blogs</h2>
        <div>
          <h3>how to learn javascript</h3>
          <p>javascript is a programming lenguage for web</p>
        </div>
        <div>
          <h3>how to learn javascript</h3>
          <p>javascript is a programming lenguage for web</p>
        </div>
        <div>
          <h3>how to learn javascript</h3>
          <p>javascript is a programming lenguage for web</p>
        </div>
        <div>
          <h3>how to learn javascript</h3>
          <p>javascript is a programming lenguage for web</p>
        </div>
        <div>
          <h3>how to learn javascript</h3>
          <p>javascript is a programming lenguage for web</p>
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
        </a> */}
      </footer>
    </div>
  )
}
